apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    name: guestbook-app

spec:
  template:
    metadata:
      name: webapp-pod
      labels:
        name: webapp-pod
        app: guestbook-app
    spec:
      containers:
        - name: webapp
          image: gcr.io/google-samples/gb-frontend:v4
          ports:
            - containerPort: 80
  replicas: 3

  selector:
    matchLabels:
      name: webapp-pod
      app: guestbook-app