apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    name: webapp-service
    app: guestbook-app
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 80
     nodePort: 30012
  selector:
    name: webapp-pod
    app: guestbook-app